# logistic regression
lr:
  solver: ['lbfgs', 'liblinear', 'newton-cg']
  max_iter: [25, 50, 100]


# k-nearest neighbors
knn:
  neighbors: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


# support vector machines
svm:
  C: [0.05, 0.1, 0.5, 1, 10]
  kernel: ['poly', 'rbf', 'sigmoid']